// Generated by BUCKLESCRIPT VERSION 1.2.1 , PLEASE EDIT WITH CARE
'use strict';


var Obj = /* module */[];

function boolean_of_bool(param) {
  if (param !== 0) {
    return true;
  }
  else {
    return false;
  }
}

exports.Obj             = Obj;
exports.boolean_of_bool = boolean_of_bool;
/* No side effect */
